### ISSUE TITLE
error

### ISSUE THREAD

**Issue by RazzyGP** [JackNoordhuis/PocketMine-Plugins#21] opened 2022-05-26 00:36 UTC
[00:33:12.069] [Server thread/CRITICAL]: ErrorException: "Undefined array key 0" (EXCEPTION) in "plugins/CombatLogger_v1.0.0.phar/src/JackNoordhuis/CombatLogger/EventListener" at line 111

**Comment by JackNoordhuis** [comment] 2022-05-27 01:17
Duplicate of #20. Will be fixed *soon*.

**Closed as completed by JackNoordhuis** 2022-05-27 01:17 UTC
Labels: duplicate
